--4. For University database execute following queries:
--Department (dept_name, building, budget)
--Instructor (inst_id, name, salary, dept_name)
--Course (course_id, title, credits, dept_name)
--Teaches (course_id, inst_id)
-- Find the average salary of the instructors who are in music dept.
-- Find the average salary in each dept.
-- Find out department name with average salary in each department where
--average salary is greater than 40000.
